language: julia

os:
    - linux

julia:
    - 1.0
    - 1.2
    - 1.3

after_success:
    - julia -e 'cd(Pkg.dir("MortarContact2D")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
